### ISSUE TITLE
TFFAnnotated lowercase name escaping

### ISSUE THREAD

**Issue by XBagon** [leoprover/scala-tptp-parser#3]
I know this library is mostly for parsing TPTP, but I use it to convert code to TPTP and then print it, which works very well.
I noticed `Typing`s `atom` is escaped with `escapeAtomicWord` and that works very well for uppercase `atom`s.
But I stumbled over a syntax error for the `TFFAnnotated`'s `name`, cause it also seems to need to be lowercase or escaped.
Is this an oversight or just not intended to be part of this library?

**Comment by lex-lex** [comment]
Hi there,
this was indeed an accidental omission. It should be resolved after the most recent commit (d669600).

Thanks for the report! Feel free to re-open this issue in case this is not, in fact, resolved.
