### ISSUE TITLE
TPTP `variable`s have to be uppercase.

### ISSUE THREAD

**Issue by XBagon** [leoprover/scala-tptp-parser#5]
See http://www.tptp.org/TPTP/SyntaxBNF.html#variable.
At the moment this isn't ensured, but it isn't just a simple missing feature like #3, cause there is no escaping mechanism like the single quotes available.

So it either would need a specific prefix in front of all variables, which probably isn't desired behaviour.
Bookkeeping of used variables names, is probably even less so.
One sensible way I could think of was checking if the given variable name is uppercase while constructing it and then returning `Try` accordingly.

For my use case I will just escape the variables myself, but I still wanted to document this issue.

**Comment by lex-lex** [comment]
Hi there, 
I'm not sure whether this should be/needs to be addressed. The parser will never produce any output data structure in which a variable has a non-uppercase name (it will throw a parsing exception). 

Of course, you can manually create such data structures -- but this cannot really be prevented given that the names are represented as Strings. One could add an assertion that throws a runtime exception when a Variable class is instantiated with an illegal name, but this also creates a computational overhead which is -- in the primary use case (parsing) -- unnecessary as the parser will (hopefully) never create such instances in the first place.

Thoughts? Comments?

**Comment by XBagon** [comment]
These are good points, I don't think a perfect solution exists. A mention in the documentation, a "safe" constructor or implementing the check for the print, but also having an unchecked print option, for usage with full performance? But other than that I can't think of ways without unnecessary performance loss.
